### PR TITLE
FR - enhanced output

### LINKED ISSUE #36: FR - enhanced output
I'd like to propose an enhancement to the output with the goal of improving debugging.

- add output options for request headers and request body (to make sure the request is as we expect it)
- add directional markers (as in `curl` to express request `>` vs. response `<`)
- automatically format body based on known content types (like `json+`)

e.g. here is a modified output of `tst/plans/build_queue.yml` where the only plan change is:
```patch
@@ -18,10 +18,16 @@ requests:
   post:
     url: "{{ base_url }}/queue/{{ response.json().0.id }}/init"
     json:
       node: "{{ node }}"
   register: build_create
+  output:
+  - request_headers
+  - request_body
+  - response_headers
+  - response_body
+  - foo
 - name: Get queued items
   get:
     url: "{{ base_url }}/queue"
   assert:
   - name: Queue is shorter than initially


```

The output is as follows:
image

I have a PR queued up if there's interest.

### PR DESCRIPTION
**Pull request by rotty3000**
resolves #36

### CODE REVIEW

**Comment by rotty3000** [comment]
I made updates to fix a small bug and resolve the CI failures.

**Comment by rotty3000** [comment]
FYI, the last failure is exactly the same I got on my system until I ran `pip install "cython<3.0.0" wheel && pip install pyyaml==5.4.1 --no-build-isolation`

**Comment by kangasta** [comment]
Yes, now the failures seem to be unrelated to your changes. I'll update the setup files so that they work with the pip versions used in CI.

**Comment by kangasta** [comment]
If you now rebase this on main, the install step should pass. I changed `setup.py` to `pyproject.toml` and updated `pyyaml` to new `v6`.

**Comment by rotty3000** [comment]
done!

**Comment by kangasta** [comment]
I added few tests, removed `body: ` prefix as it made yaml body a bit more confusing to read, and added helper function for pretty printing request/response body.

**Pull request merged**
